# NumPy

In [1]:
import numpy as np
from numpy import linalg

np.__version__

'1.14.0'

In [2]:
# Ejemplo mínimo de NumPy

v = np.array([1,2,3])
print(v)
print(v[1])

m = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(m)
print(m[2,1])

# Multiplicación vector-matriz
print(v @ m)

# Inversa de una matriz
m_inv = linalg.inv(m)
print(m_inv)

# Multiplicación matriz-matriz
print(m @ m_inv)

[1 2 3]
2
[[1 2 3]
 [0 1 4]
 [5 6 0]]
6
[16 22 11]
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
[[ 1.00000000e+00 -1.77635684e-15 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# Pandas

## Carga desde fichero

In [3]:
import pandas as pd
pd.__version__

'0.22.0'

In [4]:
# Carga el fichero 
df = pd.read_csv('../../data/Cap5/titanic.csv')

In [5]:
# Lectura de todas las hojas de 'data/Cap5/subvenciones_totales.xls', devuelve un diccionario ordenado (str, DataFrame)
subvenciones = pd.read_excel('../../data/Cap5/subvenciones_totales.xls', sheet_name=None)
print(subvenciones['Totales'])

                     Asociación  Importe total  Importe justificado  Restante
0          AMPA ANTONIO MACHADO        2344.99                    0  -2344.99
1   AMPA BACHILLER ALONSO LOPEZ        3200.00                    0  -3200.00
2                 AMPA CASTILLA        2604.44                    0  -2604.44
3          AMPA DAOIZ Y VELARDE        3152.74                    0  -3152.74
4            AMPA EMILIO CASADO        3015.67                    0  -3015.67
5    AMPA FEDERICO GARCIA LORCA        1919.06                    0  -1919.06
6          AMPA GABRIEL Y GALAN        2741.51                    0  -2741.51
7              AMPA LUIS BUÑUEL        2081.00                    0  -2081.00
8         AMPA MIGUEL HERNANDEZ        2923.35                    0  -2923.35
9               AMPA MIRAFLORES        2787.21                    0  -2787.21
10         AMPA PARQUE CATALUÑA        2604.44                    0  -2604.44
11  AMPA PROFESOR TIERNO GALVÁN        1286.00                  

## Visualizar y extraer información

In [6]:
# Visualizar el principio y final de un DataFrame
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [7]:
# Mostrar el principio y final de un DataFrame, en modo texto
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25          

In [8]:
# Índice pandas con las columnas de un DataFrame
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
# Tamaño de un DataFrame
df.shape

(891, 12)

In [10]:
# .iloc para seleccionar por posición
print(type(df.iloc))
display(df.iloc[5])   # Fila en la posición 5
display(df.iloc[:2])  # Filas en el rango [0,2)
display(df.iloc[0,0]) # Celda (0,0)
display(df.iloc[[0,10,12],3:4]) # Filas 0, 10 y 12, columnas 3:4

<class 'pandas.core.indexing._iLocIndexer'>


PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

1

Name
0           Braund, Mr. Owen Harris
10  Sandstrom, Miss. Marguerite Rut
12   Saundercock, Mr. William Henry

In [11]:
# .iloc para seleccionar usando los índices
print(type(df.loc))
display(df.loc[0])                # Fila con índice 0
display(df.loc[0,'Fare'])         # celda de la fila 0 y columna 'Fare'
display(df.loc[:3, 'Sex':'Fare']) # Filas 0:3 (incluidas) en las columnas 'Sex':'Fare' (incluidas)
display(df.loc[:3, ['Sex','Fare','Embarked']]) # Filas 0:3 (incluidas) en las columnas 'Sex','Fare' y 'Embarked'
display(df.loc[df['Age']> 70])    # Filas con 'Age' > 70
display(df.loc[df['Age']> 70, ['Age','Sex']])    # Filas con 'Age' > 70, mostrar la columna 'Sex'

<class 'pandas.core.indexing._LocIndexer'>


PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                                 22
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

7.25

Sex   Age  SibSp  Parch            Ticket     Fare
0    male  22.0      1      0         A/5 21171   7.2500
1  female  38.0      1      0          PC 17599  71.2833
2  female  26.0      0      0  STON/O2. 3101282   7.9250
3  female  35.0      1      0            113803  53.1000

Sex     Fare Embarked
0    male   7.2500        S
1  female  71.2833        C
2  female   7.9250        S
3  female  53.1000        S

PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S

Age   Sex
96   71.0  male
116  70.5  male
493  71.0  male
630  80.0  male
851  74.0  male

In [12]:
# Tipos almacenados en cada columna
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [13]:
# Descripción de los valores de un DataFrame
print(df.describe(include='all'))

        PassengerId    Survived      Pclass  \
count    891.000000  891.000000  891.000000   
unique          NaN         NaN         NaN   
top             NaN         NaN         NaN   
freq            NaN         NaN         NaN   
mean     446.000000    0.383838    2.308642   
std      257.353842    0.486592    0.836071   
min        1.000000    0.000000    1.000000   
25%      223.500000    0.000000    2.000000   
50%      446.000000    0.000000    3.000000   
75%      668.500000    1.000000    3.000000   
max      891.000000    1.000000    3.000000   

                                                     Name   Sex         Age  \
count                                                 891   891  714.000000   
unique                                                891     2         NaN   
top     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  male         NaN   
freq                                                    1   577         NaN   
mean                                    

In [14]:
# Código alternativo para calcular valores nulos y únicos

# Valores nulos
for c in df.columns:
    print("Missing values [{0}]:".format(c), df[c].isna().sum())
print()

# Valores únicos    
for c in df.columns:
    print("Unique values [{0}]:".format(c), df[c].unique().size)

Missing values [PassengerId]: 0
Missing values [Survived]: 0
Missing values [Pclass]: 0
Missing values [Name]: 0
Missing values [Sex]: 0
Missing values [Age]: 177
Missing values [SibSp]: 0
Missing values [Parch]: 0
Missing values [Ticket]: 0
Missing values [Fare]: 0
Missing values [Cabin]: 687
Missing values [Embarked]: 2

Unique values [PassengerId]: 891
Unique values [Survived]: 2
Unique values [Pclass]: 3
Unique values [Name]: 891
Unique values [Sex]: 2
Unique values [Age]: 89
Unique values [SibSp]: 7
Unique values [Parch]: 7
Unique values [Ticket]: 681
Unique values [Fare]: 248
Unique values [Cabin]: 148
Unique values [Embarked]: 4


## Transformar DataFrames

In [15]:
# Carga el fichero 
df = pd.read_csv('../../data/Cap5/titanic.csv')

# Elimina columnas no relevantes y filas con valores nulos
df = df.drop(columns=['PassengerId', 'Name', 'Ticket','Cabin'])
df = df.dropna()

# Traduce los valores categóricos de 'Sex' y 'Embarked' a número enteros
df['Sex'] = df['Sex'].astype('category').cat.codes
df['Embarked'] = df['Embarked'].astype('category').cat.codes
df

Survived  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0           0       3    1  22.0      1      0    7.2500         2
1           1       1    0  38.0      1      0   71.2833         0
2           1       3    0  26.0      0      0    7.9250         2
3           1       1    0  35.0      1      0   53.1000         2
4           0       3    1  35.0      0      0    8.0500         2
6           0       1    1  54.0      0      0   51.8625         2
7           0       3    1   2.0      3      1   21.0750         2
8           1       3    0  27.0      0      2   11.1333         2
9           1       2    0  14.0      1      0   30.0708         0
10          1       3    0   4.0      1      1   16.7000         2
11          1       1    0  58.0      0      0   26.5500         2
12          0       3    1  20.0      0      0    8.0500         2
13          0       3    1  39.0      1      5   31.2750         2
14          0       3    0  14.0      0      0    7.8542         2
15          1       2    0  55.0      0      0   16.0000         2
16          0       3    1   2.0      4      1   29.1250         1
18          0       3    0  31.0      1      0   18.0000         2
20          0       2    1  35.0      0      0   26.0000         2
21          1       2    1  34.0      0      0   13.0000         2
22          1       3    0  15.0      0      0    8.0292         1
23          1       1    1  28.0      0      0   35.5000         2
24          0       3    0   8.0      3      1   21.0750         2
25          1       3    0  38.0      1      5   31.3875         2
27          0       1    1  19.0      3      2  263.0000         2
30          0       1    1  40.0      0      0   27.7208         0
33          0       2    1  66.0      0      0   10.5000         2
34          0       1    1  28.0      1      0   82.1708         0
35          0       1    1  42.0      1      0   52.0000         2
37          0       3    1  21.0      0      0    8.0500         2
38          0       3    0  18.0      2      0   18.0000         2
..        ...     ...  ...   ...    ...    ...       ...       ...
856         1       1    0  45.0      1      1  164.8667         2
857         1       1    1  51.0      0      0   26.5500         2
858         1       3    0  24.0      0      3   19.2583         0
860         0       3    1  41.0      2      0   14.1083         2
861         0       2    1  21.0      1      0   11.5000         2
862         1       1    0  48.0      0      0   25.9292         2
864         0       2    1  24.0      0      0   13.0000         2
865         1       2    0  42.0      0      0   13.0000         2
866         1       2    0  27.0      1      0   13.8583         0
867         0       1    1  31.0      0      0   50.4958         2
869         1       3    1   4.0      1      1   11.1333         2
870         0       3    1  26.0      0      0    7.8958         2
871         1       1    0  47.0      1      1   52.5542         2
872         0       1    1  33.0      0      0    5.0000         2
873         0       3    1  47.0      0      0    9.0000         2
874         1       2    0  28.0      1      0   24.0000         0
875         1       3    0  15.0      0      0    7.2250         0
876         0       3    1  20.0      0      0    9.8458         2
877         0       3    1  19.0      0      0    7.8958         2
879         1       1    0  56.0      0      1   83.1583         0
880         1       2    0  25.0      0      1   26.0000         2
881         0       3    1  33.0      0      0    7.8958         2
882         0       3    0  22.0      0      0   10.5167         2
883         0       2    1  28.0      0      0   10.5000         2
884         0       3    1  25.0      0      0    7.0500         2
885         0       3    0  39.0      0      5   29.1250         1
886         0       2    1  27.0      0      0   13.0000         2
887         1       1    0  19.0      0      0   30.

## Salvar a ficheros

In [16]:
# A formato CSV
df.to_csv('../../data/Cap5/titanic_ml.csv', index=False)

# A formato Excel (XLS y XLSX)
# La hoja se llamará 'Sheet1'
df.to_excel('../../data/Cap5/titanic_ml.xls', index=False)
df.to_excel('../../data/Cap5/titanic_ml.xlsx', index=False)

In [17]:
# Insertar varias hojas en un fichero Excel
writer = pd.ExcelWriter('../../data/Cap5/titanic_2.xlsx')
df.to_excel(writer, sheet_name='Hoja 1', index=False)
df.to_excel(writer, sheet_name='Hoja 2', index=False)
writer.close()

# Aprendizaje automático con Scikit-learn

In [18]:
# Versión de scikit-learn
import sklearn
sklearn.__version__

'0.19.1'

## Preprocesado

In [19]:
# Función para partir un DataFrame en train+test y separar también la columna clase
from sklearn.model_selection import train_test_split

def split_label(df, test_size, label):
    train, test = train_test_split(df, test_size=test_size)
    features = df.columns.drop(label)
    train_X = train[features]
    train_y = train[label]
    test_X = test[features]
    test_y = test[label]
    
    return train_X, train_y, test_X, test_y   

In [20]:
# División en train (80%) y test (20%) para clasificación, con clase 'Survived'
titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')
train_X, train_y, test_X, test_y = split_label(titanic, 0.2, 'Survived')

# train_X y test_X son DataFrames
# train_y y test_y son Series

In [21]:
# One hot encoding de la columna 'Embarked'
from sklearn.preprocessing import OneHotEncoder

index_Embarked = train_X.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)
train_X_1 = ohe.fit_transform(train_X)

# train_X_1 es un objeto ndarray de tamaño (569, 9) y tipo float64
print(type(train_X_1))
print(train_X_1.shape)
print(train_X_1.dtype)

<class 'numpy.ndarray'>
(569, 9)
float64


In [22]:
# Escalado al rango [0,1] de todos los atributos
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
train_X_2 = min_max_scaler.fit_transform(train_X_1)

print(type(train_X_2))
print(train_X_2.shape)
print(train_X_2.dtype)

# Muestra las 3 primeras entradas de train_X_2
for i in range(3): 
    print(train_X_2[i])

<class 'numpy.ndarray'>
(569, 9)
float64
[1.         0.         0.         0.         1.         0.43453129
 0.         0.         1.        ]
[0.         0.         1.         0.5        0.         0.50992712
 0.         0.2        0.03806147]
[1.         0.         0.         0.         0.         0.22090978
 0.4        0.4        0.51212189]


## Clasificación

In [23]:
from sklearn.svm import SVC

# Entrenamiento
clf = SVC()
clf.fit(train_X_2, train_y)

# Transformación del conjunto de test (one hot encoding y escalado)
print(test_X.shape)
test_X_2 = min_max_scaler.transform(ohe.transform(test_X))
print(test_X_2.shape)

# Evaluación del modelo mediante precisión
print("Precisión sobre test:", clf.score(test_X_2, test_y)) 

# Uso del modelo
clf.predict(test_X_2)

(143, 7)
(143, 9)
Precisión sobre test: 0.7902097902097902


array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1])

In [24]:
# Clasificación usando kNN
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()
clf.fit(train_X_2, train_y)

# Evaluación del modelo mediante precisión
print("Precisión sobre test:", clf.score(test_X_2, test_y)) 

Precisión sobre test: 0.8111888111888111


## Regresión

In [25]:
# Regresión lineal
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

# separación train-test con clase 'Fare'
titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')
train_X, train_y, test_X, test_y = split_label(titanic, 0.2, 'Fare')

# one hot encoding
index_Embarked = train_X.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)
train_X_1 = ohe.fit_transform(train_X)

# Escalado de atributos al rango [0,1]
min_max_scaler = MinMaxScaler()
train_X_2 = min_max_scaler.fit_transform(train_X_1)

# Entrenamiento
reg = LinearRegression()
reg.fit(train_X_2, train_y)

# Transformación del conjunto de test (one hot encoding y escalado)
test_X_2 = min_max_scaler.transform(ohe.transform(test_X))

# Evaluación del modelo mediante métrica R^2 y MSE
print("R^2:", reg.score(test_X_2, test_y)) 

# Uso y evaluación del modelo con MSE
pred = reg.predict(test_X_2)
print("MSE:", mean_squared_error(test_y, pred))
print("MAE:", mean_absolute_error(test_y, pred))

R^2: 0.33006209505981854
MSE: 2281.8830855762235
MAE: 24.65608671328671


In [26]:
# Regresión usando kNN
from sklearn.neighbors import KNeighborsRegressor

reg = LinearRegression()
reg.fit(train_X_2, train_y)

# Evaluación del modelo mediante métrica R^2
print("R^2:", reg.score(test_X_2, test_y)) 

# Uso y evaluación del modelo con MSE y MAE
pred = reg.predict(test_X_2)
print("MSE:", mean_squared_error(test_y, pred))
print("MAE:", mean_absolute_error(test_y, pred))

R^2: 0.33006209505981854
MSE: 2281.8830855762235
MAE: 24.65608671328671


## Clustering

In [27]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabaz_score

titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')

# one hot encoding
index_Embarked = titanic.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)
titanic_1 = ohe.fit_transform(titanic)

# Escalado de atributos al rango [0,1]
min_max_scaler = MinMaxScaler()
titanic_2 = min_max_scaler.fit_transform(titanic_1)

# Clustering
clu = KMeans(n_clusters=3)
clu.fit(titanic_2)
print("Centros de los clústeres:\n", clu.cluster_centers_)

# Evaluación de los clústeres
print('silhouette_score:', silhouette_score(titanic_2, clu.labels_))
print('calinski_harabaz:', calinski_harabaz_score(titanic_2, clu.labels_))

# Comprobar distancia a cada centroide para las instancias de titanic_2 (podrían ser otro conjunto de datos)
clu.transform(titanic_2)

Centros de los clústeres:
 [[ 3.33066907e-16  3.79146919e-02  9.62085308e-01  9.90521327e-01
   4.95260664e-01  3.27014218e-01  3.43576883e-01  9.95260664e-02
   9.47867299e-02  7.78150129e-02]
 [ 1.22124533e-15  5.39083558e-02  9.46091644e-01 -2.60902411e-15
   7.77628032e-01  8.49056604e-01  3.75477998e-01  1.11051213e-01
   6.01976640e-02  3.85185852e-02]
 [ 1.00000000e+00 -9.02056208e-17  1.22124533e-15  6.07692308e-01
   3.73076923e-01  5.30769231e-01  3.81939799e-01  8.46153846e-02
   6.92307692e-02  1.33306411e-01]]
silhouette_score: 0.4036033588295353
calinski_harabaz: 369.21898121397436


array([[1.31150832, 0.31789029, 1.73984874],
       [1.52274362, 2.0626726 , 0.77530662],
       [0.62284202, 1.33998748, 1.69060722],
       ...,
       [0.62174709, 1.53881024, 1.6169074 ],
       [1.62637004, 1.88275404, 0.73107457],
       [1.88829988, 1.37090166, 1.73454341]])

## Pipelines

### Clasificación

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

## Preprocesado

# División en train (80%) y test (20%) para clasificación, con clase 'Survived'
titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')
train_X, train_y, test_X, test_y = split_label(titanic, 0.2, 'Survived')

# Etapa one hot encoding
index_Embarked = train_X.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)

# Etapa de escalado de atributos al rango [0,1]
min_max_scaler = MinMaxScaler()

# Etapa de clasificación
svm = SVC()

# Creación del pipeline
pipe = Pipeline([('ohe', ohe), ('sca', min_max_scaler), ('clf', svm)])

# Entranamiento del pipeline
pipe.fit(train_X, train_y)

# Evaluación del pipeline
print('precisión:', pipe.score(test_X, test_y))

# Uso del modelo
pipe.predict(test_X)

precisión: 0.7762237762237763


array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0])

### Regresión

In [29]:
# Pipeline para regresión

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

## Preprocesado

# División en train (80%) y test (20%) para clasificación, con clase 'Fare'
titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')
train_X, train_y, test_X, test_y = split_label(titanic, 0.2, 'Fare')

# Etapa de one hot encoding
index_Embarked = train_X.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)

# Etapa de escalado de atributos al rango [0,1]
min_max_scaler = MinMaxScaler()

# Etapa de regresión
lin = LinearRegression()

# Creación del pipeline
pipe = Pipeline([('ohe', ohe), ('sca', min_max_scaler), ('reg', lin)])

# Entranamiento del pipeline
pipe.fit(train_X, train_y)

# Evaluación R^2 del pipeline
print('R^2:', pipe.score(test_X, test_y))

# Uso del modelo y evaluación MSE
pred = pipe.predict(test_X)
print(pred)
print('MSE:', mean_squared_error(test_y, pred))
print("MAE:", mean_absolute_error(test_y, pred))

R^2: 0.4655358970092498
[ 4.23624410e+01 -7.88707722e+00  2.09158841e+01  2.82841332e+01
  9.44019909e+01  9.54023341e+01 -1.57835885e+00  3.67643341e+01
  7.42041671e+01  8.81631115e+01  6.60580792e+01 -4.18580758e+00
  9.33814781e+01  8.20941878e+01  5.16619653e+01  1.41936956e+01
  5.99071043e+01  9.00917723e+01  2.32516593e+00  4.61513350e+01
  1.68623079e+01  4.88709478e+01 -8.82488682e-01  2.60833783e+01
  5.35906261e+01 -3.48556738e+00  5.08551343e+01  7.04938742e+01
  1.23930779e+01  6.89656309e+01 -3.78567033e+00  6.00538338e+01
  6.96015522e+01  5.37380026e+00  8.95635919e+01  6.18544515e+01
  5.63714026e+01  2.05307181e+00 -8.22141667e-02  5.24743697e+01
  6.09541426e+01 -4.58594484e+00 -5.68632230e+00  2.42520025e+00
  2.75838930e+01 -3.78567033e+00  4.71209224e+01  2.16614565e+00
  8.89633860e+01 -4.18580758e+00 -5.53868309e+00  5.25678474e+01
  3.27944204e+01 -4.98608210e+00  1.06442580e+02 -3.98573895e+00
  5.53753648e+01  2.47237446e+01  5.01145400e+01  4.48350099e+01
 

### Clustering

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans

titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')

# Etapa de one hot encoding
index_Embarked = titanic.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)

# Etapa de escalado en rango [0,1]
sca = MinMaxScaler()

# Etapa de clustering
clu = KMeans(n_clusters=3)

# Creación del pipeline
pipe = Pipeline([('ohe', ohe), ('sca', sca), ('clu',clu)])

# Entrenamiento del pipeline
pipe.fit(titanic)
print("Centros de los clústeres:\n", pipe.named_steps['clu'].cluster_centers_)

# Evaluación de los clústeres
print('silhouette_score:', silhouette_score(titanic_2, pipe.named_steps['clu'].labels_))
print('calinski_harabaz:', calinski_harabaz_score(titanic_2, pipe.named_steps['clu'].labels_))

Centros de los clústeres:
 [[ 3.33066907e-16  3.79146919e-02  9.62085308e-01  9.90521327e-01
   4.95260664e-01  3.27014218e-01  3.43576883e-01  9.95260664e-02
   9.47867299e-02  7.78150129e-02]
 [ 1.00000000e+00 -9.02056208e-17  1.22124533e-15  6.07692308e-01
   3.73076923e-01  5.30769231e-01  3.81939799e-01  8.46153846e-02
   6.92307692e-02  1.33306411e-01]
 [ 1.22124533e-15  5.39083558e-02  9.46091644e-01 -2.60902411e-15
   7.77628032e-01  8.49056604e-01  3.75477998e-01  1.11051213e-01
   6.01976640e-02  3.85185852e-02]]
silhouette_score: 0.4036033588295353
calinski_harabaz: 369.21898121397425


## Persistencia de modelos

In [31]:
# Salvar un modelo de clustering k-means
from sklearn.externals import joblib

titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')

index_Embarked = titanic.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)
titanic_1 = ohe.fit_transform(titanic)
min_max_scaler = MinMaxScaler()
titanic_2 = min_max_scaler.fit_transform(titanic_1)

clu = KMeans(n_clusters=3)
clu.fit(titanic_2)

print("Centros de los clústeres:\n", clu.cluster_centers_)
print('silhouette_score:', silhouette_score(titanic_2, clu.labels_))
print('calinski_harabaz:', calinski_harabaz_score(titanic_2, clu.labels_))

joblib.dump(clu, '../../data/Cap5/kmeans.pkl')

Centros de los clústeres:
 [[ 3.33066907e-16  3.79146919e-02  9.62085308e-01  9.90521327e-01
   4.95260664e-01  3.27014218e-01  3.43576883e-01  9.95260664e-02
   9.47867299e-02  7.78150129e-02]
 [ 1.22124533e-15  5.39083558e-02  9.46091644e-01 -2.60902411e-15
   7.77628032e-01  8.49056604e-01  3.75477998e-01  1.11051213e-01
   6.01976640e-02  3.85185852e-02]
 [ 1.00000000e+00 -9.02056208e-17  1.22124533e-15  6.07692308e-01
   3.73076923e-01  5.30769231e-01  3.81939799e-01  8.46153846e-02
   6.92307692e-02  1.33306411e-01]]
silhouette_score: 0.4036033588295353
calinski_harabaz: 369.21898121397436


['../../data/Cap5/kmeans.pkl']

In [32]:
# Cargar y utilizar un modelo de clustering k-means
loaded_clu = joblib.load('../../data/Cap5/kmeans.pkl') 

print("Centros de los clústeres:\n", clu.cluster_centers_)
print('silhouette_score:', silhouette_score(titanic_2, clu.labels_))
print('calinski_harabaz:', calinski_harabaz_score(titanic_2, clu.labels_))
clu.transform(titanic_2)

Centros de los clústeres:
 [[ 3.33066907e-16  3.79146919e-02  9.62085308e-01  9.90521327e-01
   4.95260664e-01  3.27014218e-01  3.43576883e-01  9.95260664e-02
   9.47867299e-02  7.78150129e-02]
 [ 1.22124533e-15  5.39083558e-02  9.46091644e-01 -2.60902411e-15
   7.77628032e-01  8.49056604e-01  3.75477998e-01  1.11051213e-01
   6.01976640e-02  3.85185852e-02]
 [ 1.00000000e+00 -9.02056208e-17  1.22124533e-15  6.07692308e-01
   3.73076923e-01  5.30769231e-01  3.81939799e-01  8.46153846e-02
   6.92307692e-02  1.33306411e-01]]
silhouette_score: 0.4036033588295353
calinski_harabaz: 369.21898121397436


array([[1.31150832, 0.31789029, 1.73984874],
       [1.52274362, 2.0626726 , 0.77530662],
       [0.62284202, 1.33998748, 1.69060722],
       ...,
       [0.62174709, 1.53881024, 1.6169074 ],
       [1.62637004, 1.88275404, 0.73107457],
       [1.88829988, 1.37090166, 1.73454341]])

In [33]:
# Salvar pipeline de clustering k-means
titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')

index_Embarked = titanic.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)
sca = MinMaxScaler()
clu = KMeans(n_clusters=3)

pipe = Pipeline([('ohe', ohe), ('sca', sca), ('clu',clu)])
pipe.fit(titanic)

print("Centros de los clústeres:\n", pipe.named_steps['clu'].cluster_centers_)
print('silhouette_score:', silhouette_score(titanic_2, pipe.named_steps['clu'].labels_))
print('calinski_harabaz:', calinski_harabaz_score(titanic_2, pipe.named_steps['clu'].labels_))

joblib.dump(pipe, '../../data/Cap5/kmeans_pipeline.pkl')

Centros de los clústeres:
 [[ 1.22124533e-15  5.39083558e-02  9.46091644e-01 -2.60902411e-15
   7.77628032e-01  8.49056604e-01  3.75477998e-01  1.11051213e-01
   6.01976640e-02  3.85185852e-02]
 [ 3.33066907e-16  3.79146919e-02  9.62085308e-01  9.90521327e-01
   4.95260664e-01  3.27014218e-01  3.43576883e-01  9.95260664e-02
   9.47867299e-02  7.78150129e-02]
 [ 1.00000000e+00 -9.02056208e-17  1.22124533e-15  6.07692308e-01
   3.73076923e-01  5.30769231e-01  3.81939799e-01  8.46153846e-02
   6.92307692e-02  1.33306411e-01]]
silhouette_score: 0.4036033588295353
calinski_harabaz: 369.21898121397436


['../../data/Cap5/kmeans_pipeline.pkl']

In [34]:
# Cargar y utilizar un pipeline de clustering k-means
loaded_pipe = joblib.load('../../data/Cap5/kmeans_pipeline.pkl') 

print("Centros de los clústeres:\n", loaded_pipe.named_steps['clu'].cluster_centers_)
print('silhouette_score:', silhouette_score(titanic_2, loaded_pipe.named_steps['clu'].labels_))
print('calinski_harabaz:', calinski_harabaz_score(titanic_2, loaded_pipe.named_steps['clu'].labels_))

Centros de los clústeres:
 [[ 1.22124533e-15  5.39083558e-02  9.46091644e-01 -2.60902411e-15
   7.77628032e-01  8.49056604e-01  3.75477998e-01  1.11051213e-01
   6.01976640e-02  3.85185852e-02]
 [ 3.33066907e-16  3.79146919e-02  9.62085308e-01  9.90521327e-01
   4.95260664e-01  3.27014218e-01  3.43576883e-01  9.95260664e-02
   9.47867299e-02  7.78150129e-02]
 [ 1.00000000e+00 -9.02056208e-17  1.22124533e-15  6.07692308e-01
   3.73076923e-01  5.30769231e-01  3.81939799e-01  8.46153846e-02
   6.92307692e-02  1.33306411e-01]]
silhouette_score: 0.4036033588295353
calinski_harabaz: 369.21898121397436


## Optimización de hiperparámetros

In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn import svm
import pandas as pd

# División en train (80%) y test (20%) para clasificación, con clase 'Survived'
titanic = pd.read_csv('../../data/Cap5/titanic_ml.csv')
train_X, train_y, test_X, test_y = split_label(titanic, 0.2, 'Survived')

index_Embarked = train_X.columns.get_loc('Embarked')
ohe = OneHotEncoder(categorical_features=[index_Embarked], sparse=False)
train_X_1 = ohe.fit_transform(train_X)

min_max_scaler = MinMaxScaler()
train_X_2 = min_max_scaler.fit_transform(train_X_1)

svc = svm.SVC()

parameters = {'kernel': ['linear', 'rbf'], 'C':[1,2] }
clf = GridSearchCV(svc, parameters, n_jobs=4)
clf.fit(train_X, train_y)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=4,
       param_grid={'kernel': ['linear', 'rbf'], 'C': [1, 2]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [36]:
print(clf.best_params_)
print(clf.best_score_)
print(clf.best_estimator_)

print(clf.score(test_X, test_y))
clf.predict(test_X)

{'C': 1, 'kernel': 'linear'}
0.7768014059753954
SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.7902097902097902


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1])